### ISSUE TITLE
Update for Intern 4

### ISSUE THREAD

**Issue by jason0x43** [theintern/visual-plugin#10]
Update this project for Intern 4:

- Ensure it works with Intern 4
- Update dependencies
- Publish under @theintern org

**Comment by jason0x43** [comment]
Dependencies have been updated and the code has been updated to work with tsc's strict settings.

Step two is to either remove the plugin's reliance on intern's config data (so it's more version-agnostic), or update it to use Intern 4's config.

**Comment by dbow** [comment]
Any sense of when this might be updated to work with Intern 4 config?

**Comment by jason0x43** [comment]
This is resolved in version 0.2.0. Note that the package name has changed to `@theintern/visual-plugin`.
